import
without bracket element 0D
list form elements
tuples for element
list kae undar list
type
dimesniond
mdimin
ones mtd
zero mtd
eye mtd
flaten mtd
reshape
arrange
3D accesing elements




In [67]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [68]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [69]:
arr = np.array([[1,2,3,4,5],[10,9,8,7,6]])
print(arr)
type(arr)

[[ 1  2  3  4  5]
 [10  9  8  7  6]]


numpy.ndarray

In [70]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [71]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [72]:
arr = np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [73]:
arr = np.ones((2,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [74]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [75]:
arr = np.arange(0,10,3)
print(arr)

[0 3 6 9]


In [117]:
arr = np.random.uniform(0,10,3)
print(arr)

[8.62568967 5.01026066 8.21169219]


In [118]:
arr = np.random.randint(0,10,3)
print(arr)

[9 4 3]


In [77]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [78]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [80]:
arr = np.array([[1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10]])
print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10]


ASSignment 1c - Perform matrix additon, subraction and multiplication using Numpy library

In [91]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [92]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [107]:
print(a1+a2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [108]:
print(a1-a2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [93]:
print(a1*a2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [104]:
c = np.dot(a1,a2)
print(c)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [106]:
c = np.multiply(a1,a2)
print(c)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
